# CONSTANTES
WIDTH = 256
HEIGHT = 256
CAPTION = "DonkeyKong por Alvaro García y Hugo García"
FPS = 30
POSXBARRIL = 68
POSYBARRIL = 40
SPRITEBARRIL = 1
VELOCIDADBARRIL = 2
VELOCIDADBARRILBAJANDO = 1
CTESALTOMARIO = 8
TIEMPOSALTOMARIO = 1